server:
  port: 8486
spring:
  application:
    name: Drivz-SocketServer
#  datasource:
#    username: root
#    password: Seraj@123
#    url: jdbc:mysql:3306
 
  kafka:
    bootstrap-servers: localhost:9092  
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: sample-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
  

